# Class one Python 101

## Overview

In [29]:
#pip install yfinance==0.2.35

In [2]:
import pandas as pd
import yfinance as yf

In [4]:
# print() is a function in python
print("hello")
print("hello again")

hello
hello again

## Data types

In [32]:
a=10

In [33]:
type(a)

int

In [34]:
a=a+1

In [35]:
a

11

In [36]:
b=10.1

In [37]:
type(b)

float

In [38]:
c="Peter Chan"

In [39]:
type(c)

str

In [40]:
a="hello"

In [41]:
a

'hello'

In [42]:
e=True

In [43]:
e

True

In [44]:
f=False

In [45]:
#g=true

## List

In [46]:
L=[1,2,4]

In [47]:
L

[1, 2, 4]

In [48]:
len(L)

3

In [49]:
L1=[[1,2,3],[4,5,6],9,10.1,True]

In [50]:
L1[0]

[1, 2, 3]

In [51]:
len(L1)

5

## Dictionary

In [52]:
D={"Peter":10000,"Nancy":20000,"David":30000}

In [53]:
D

{'Peter': 10000, 'Nancy': 20000, 'David': 30000}

In [54]:
D["Peter"]

10000

In [6]:
# df is a dataframe from pandas
df=yf.download("^HSI","2021-01-01")

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

In [8]:
df

Price              Close          High           Low          Open      Volume
Ticker              ^HSI          ^HSI          ^HSI          ^HSI        ^HSI
Date
2021-01-04  27472.810547  27502.830078  27079.240234  27087.130859  2870443300
2021-01-05  27649.859375  27690.210938  27150.380859  27281.339844  3282490100
2021-01-06  27692.300781  27756.429688  27389.779297  27613.339844  3079382600
2021-01-07  27548.519531  27752.359375  27457.470703  27715.939453  3775142800
2021-01-08  27878.220703  27920.769531  27538.199219  27630.029297  5667284000
...                  ...           ...           ...           ...         ...
2025-04-25  21980.740234  22267.960938  21923.900391  22080.439453  3025700000
2025-04-28  21971.960938  22072.349609  21817.849609  22072.349609  2466000000
2025-04-29  22008.109375  22213.509766  21918.099609  22073.359375  3045200000
2025-04-30  22119.410156  22129.310547  21848.330078  22038.730469  4682300000
2025-05-02  22504.679688  22532.539062  22058.300781  22192.509766           0

[1062 rows x 5 columns]

In [10]:
df.tail()

Price              Close          High           Low          Open      Volume
Ticker              ^HSI          ^HSI          ^HSI          ^HSI        ^HSI
Date
2025-04-25  21980.740234  22267.960938  21923.900391  22080.439453  3025700000
2025-04-28  21971.960938  22072.349609  21817.849609  22072.349609  2466000000
2025-04-29  22008.109375  22213.509766  21918.099609  22073.359375  3045200000
2025-04-30  22119.410156  22129.310547  21848.330078  22038.730469  4682300000
2025-05-02  22504.679688  22532.539062  22058.300781  22192.509766           0

In [12]:
df.head()

Price              Close          High           Low          Open      Volume
Ticker              ^HSI          ^HSI          ^HSI          ^HSI        ^HSI
Date
2021-01-04  27472.810547  27502.830078  27079.240234  27087.130859  2870443300
2021-01-05  27649.859375  27690.210938  27150.380859  27281.339844  3282490100
2021-01-06  27692.300781  27756.429688  27389.779297  27613.339844  3079382600
2021-01-07  27548.519531  27752.359375  27457.470703  27715.939453  3775142800
2021-01-08  27878.220703  27920.769531  27538.199219  27630.029297  5667284000

In [14]:
df.describe()

Price          Close          High           Low          Open        Volume
Ticker          ^HSI          ^HSI          ^HSI          ^HSI          ^HSI
count    1062.000000   1062.000000   1062.000000   1062.000000  1.062000e+03
mean    21196.078751  21381.215903  21007.183717  21206.077257  2.623480e+09
std      3906.156279   3921.634542   3882.319938   3918.242117  1.118858e+09
min     14687.019531  15113.150391  14597.309570  14830.690430  0.000000e+00
25%     18081.699707  18207.964844  17937.842285  18069.897461  1.937923e+09
50%     20102.419922  20284.094727  19955.354492  20135.109375  2.379908e+09
75%     23778.277832  23959.524414  23511.132324  23701.814941  2.993609e+09
max     31084.939453  31183.359375  30570.550781  31183.359375  1.268650e+10

In [16]:
# It is a series in pandas
df["Close"]

Ticker              ^HSI
Date
2021-01-04  27472.810547
2021-01-05  27649.859375
2021-01-06  27692.300781
2021-01-07  27548.519531
2021-01-08  27878.220703
...                  ...
2025-04-25  21980.740234
2025-04-28  21971.960938
2025-04-29  22008.109375
2025-04-30  22119.410156
2025-05-02  22504.679688

[1062 rows x 1 columns]

In [18]:
df["High"]

Ticker              ^HSI
Date
2021-01-04  27502.830078
2021-01-05  27690.210938
2021-01-06  27756.429688
2021-01-07  27752.359375
2021-01-08  27920.769531
...                  ...
2025-04-25  22267.960938
2025-04-28  22072.349609
2025-04-29  22213.509766
2025-04-30  22129.310547
2025-05-02  22532.539062

[1062 rows x 1 columns]

In [20]:
df["Open"]

Ticker              ^HSI
Date
2021-01-04  27087.130859
2021-01-05  27281.339844
2021-01-06  27613.339844
2021-01-07  27715.939453
2021-01-08  27630.029297
...                  ...
2025-04-25  22080.439453
2025-04-28  22072.349609
2025-04-29  22073.359375
2025-04-30  22038.730469
2025-05-02  22192.509766

[1062 rows x 1 columns]

In [22]:
df["High"]-df["Open"]

Ticker            ^HSI
Date
2021-01-04  415.699219
2021-01-05  408.871094
2021-01-06  143.089844
2021-01-07   36.419922
2021-01-08  290.740234
...                ...
2025-04-25  187.521484
2025-04-28    0.000000
2025-04-29  140.150391
2025-04-30   90.580078
2025-05-02  340.029297

[1062 rows x 1 columns]

In [24]:
df["High_Open"]=df["High"]-df["Open"]

In [26]:
df.tail()

Price,Close,High,Low,Open,Volume,High_Open
Ticker,^HSI,^HSI,^HSI,^HSI,^HSI,
Date,,,,,,
2025-04-25,21980.740234,22267.960938,21923.900391,22080.439453,3025700000,187.521484
2025-04-28,21971.960938,22072.349609,21817.849609,22072.349609,2466000000,0.000000
2025-04-29,22008.109375,22213.509766,21918.099609,22073.359375,3045200000,140.150391
2025-04-30,22119.410156,22129.310547,21848.330078,22038.730469,4682300000,90.580078
2025-05-02,22504.679688,22532.539062,22058.300781,22192.509766,0,340.029297

In [28]:
df["High_Open"].describe()

count    1062.000000
mean      175.138646
std       165.066011
min         0.000000
25%        56.153320
50%       134.991211
75%       253.848145
max      1378.140625
Name: High_Open, dtype: float64

In [30]:
df["High_Open"].quantile(0.85)

323.367578125

In [32]:
df["High_Open"].quantile([0.8,0.85,0.9])

0.80    290.642188
0.85    323.367578
0.90    379.543848
Name: High_Open, dtype: float64

Class exercise
Let's compare the following calcualtion on ^HSI and 3690.HK
First calculate the following value for ^HSI and 3690.HK
High_Low=100*(High-Low)/Close
Then compare the values

In [34]:
df["High_Low"]=100*(df["High"]-df["Low"])/df["Close"]

In [36]:
df.tail()

Price,Close,High,Low,Open,Volume,High_Open,High_Low
Ticker,^HSI,^HSI,^HSI,^HSI,^HSI,,
Date,,,,,,,
2025-04-25,21980.740234,22267.960938,21923.900391,22080.439453,3025700000,187.521484,1.565282
2025-04-28,21971.960938,22072.349609,21817.849609,22072.349609,2466000000,0.000000,1.158294
2025-04-29,22008.109375,22213.509766,21918.099609,22073.359375,3045200000,140.150391,1.342279
2025-04-30,22119.410156,22129.310547,21848.330078,22038.730469,4682300000,90.580078,1.270289
2025-05-02,22504.679688,22532.539062,22058.300781,22192.509766,0,340.029297,2.107287

In [38]:
df["High_Low"].mean()

1.7875218187158592

In [40]:
df["High_Low"].max()

10.223924253788038

In [42]:
df["High_Low"].min()

0.5569307947166724

## Exporting to excel

In [76]:
df.to_excel("C:/temp/df1.xlsx")