# Class two Data management with Pandas

## Overview

In this notebook we will cover the followings:
-Data filtering with pandas 
-Data aggregation with pandas

In [2]:
#pip install yfinance

There are three methods of data filtering in pandas:
-By position
-By boolean series
-By index

In [10]:
import pandas as pd
import yfinance as yf
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])

In [3]:
type(data)

pandas.core.series.Series

In [4]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

## Filtering by position

In [5]:
data.iloc[0]

0.25

In [6]:
data.iloc[-1]

1.0

In [7]:
data.iloc[:2]

a    0.25
b    0.50
dtype: float64

In [8]:
data.iloc[-2:]

c    0.75
d    1.00
dtype: float64

### Example

In [11]:
df=yf.download("^HSI","2020-01-01")

[*********************100%%**********************]  1 of 1 completed

In [12]:
df.tail()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2024-12-18,19884.539062,19953.529297,19802.220703,19864.550781,19864.550781,2288100000
2024-12-19,19610.099609,19849.029297,19591.490234,19752.509766,19752.509766,2385000000
2024-12-20,19697.060547,19875.900391,19692.679688,19720.699219,19720.699219,3501200000
2024-12-23,19843.650391,19937.390625,19746.460938,19883.130859,19883.130859,3403600000
2024-12-24,19911.500000,20165.460938,19908.570312,20098.289062,20098.289062,2206500000

In [13]:
S_Close=df["Close"]

In [14]:
S_Close

Date
2020-01-02    28543.519531
2020-01-03    28451.500000
2020-01-06    28226.189453
2020-01-07    28322.060547
2020-01-08    28087.919922
                  ...
2024-12-18    19864.550781
2024-12-19    19752.509766
2024-12-20    19720.699219
2024-12-23    19883.130859
2024-12-24    20098.289062
Name: Close, Length: 1227, dtype: float64

Calculate the daily return:
100*(Close price on last day-close price of previous day)/(close price of previous day)

In [15]:
daily_return=100*(S_Close.iloc[-1]-S_Close.iloc[-2])/S_Close.iloc[-2]

In [16]:
daily_return

1.0821143040636971

In [17]:
S_Close.head()

Date
2020-01-02    28543.519531
2020-01-03    28451.500000
2020-01-06    28226.189453
2020-01-07    28322.060547
2020-01-08    28087.919922
Name: Close, dtype: float64

## Use of shift() in pandas

In [18]:
S_Close.shift().head()

Date
2020-01-02             NaN
2020-01-03    28543.519531
2020-01-06    28451.500000
2020-01-07    28226.189453
2020-01-08    28322.060547
Name: Close, dtype: float64

In [23]:
S_daily_return=100*(S_Close-S_Close.shift())/S_Close.shift()

In [24]:
S_daily_return

Date
2020-01-02         NaN
2020-01-03   -0.322383
2020-01-06   -0.791911
2020-01-07    0.339653
2020-01-08   -0.826708
                ...
2024-09-23   -0.062770
2024-09-24    4.129154
2024-09-25    0.676501
2024-09-26    4.158484
2024-09-27    3.551998
Name: Close, Length: 1167, dtype: float64

In [25]:
S_daily_return.describe()

count    1166.000000
mean       -0.015784
std         1.555641
min        -6.356314
25%        -0.936486
50%        -0.025371
75%         0.828116
max         9.081796
Name: Close, dtype: float64

In [26]:
S_daily_return.quantile(0.95)

2.475176342714379

In [27]:
S_daily_return.abs().describe()

count    1166.000000
mean        1.150878
std         1.046236
min         0.001947
25%         0.379845
50%         0.873761
75%         1.657322
max         9.081796
Name: Close, dtype: float64

## Filtering by boolean series

### Boolean values

In [28]:
True

True

In [29]:
False

False

In [30]:
1==1

True

In [31]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [32]:
data>0.6

a    False
b    False
c     True
d     True
dtype: bool

In [33]:
data[data>0.6]

c    0.75
d    1.00
dtype: float64

In [34]:
(data>0.6)

a    False
b    False
c     True
d     True
dtype: bool

In [35]:
(data<1)

a     True
b     True
c     True
d    False
dtype: bool

In [37]:
# & is the logical AND operation
# | is the logical OR operation
(data>0.6) & (data<1)

a    False
b    False
c     True
d    False
dtype: bool

In [39]:
S_daily_return[S_daily_return==S_daily_return.max()]

Date
2022-03-16    9.081796
Name: Close, dtype: float64

In [41]:
S_daily_return

Date
2020-01-02         NaN
2020-01-03   -0.322383
2020-01-06   -0.791911
2020-01-07    0.339653
2020-01-08   -0.826708
                ...
2024-09-23   -0.062770
2024-09-24    4.129154
2024-09-25    0.676501
2024-09-26    4.158484
2024-09-27    3.551998
Name: Close, Length: 1167, dtype: float64

In [42]:
S_daily_return>=1

Date
2020-01-02    False
2020-01-03    False
2020-01-06    False
2020-01-07    False
2020-01-08    False
              ...
2024-09-23    False
2024-09-24     True
2024-09-25    False
2024-09-26     True
2024-09-27     True
Name: Close, Length: 1167, dtype: bool

In [43]:
S_daily_return[S_daily_return>=1]

Date
2020-01-09    1.684283
2020-01-13    1.106006
2020-01-22    1.271055
2020-02-04    1.210306
2020-02-06    2.639212
                ...
2024-09-19    1.999662
2024-09-20    1.362394
2024-09-24    4.129154
2024-09-26    4.158484
2024-09-27    3.551998
Name: Close, Length: 257, dtype: float64

In [44]:
len(S_daily_return[S_daily_return>=1])

257

In [46]:
(S_daily_return>=1).sum()

257

## Filtering by index

In [47]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [48]:
data.loc["a"]

0.25

In [49]:
data.loc["a":"c"]

a    0.25
b    0.50
c    0.75
dtype: float64

In [50]:
data.loc["b":]

b    0.50
c    0.75
d    1.00
dtype: float64

In [51]:
data.loc[["a","d"]]

a    0.25
d    1.00
dtype: float64

In [52]:
S_daily_return.loc["2024-08-01":]

Date
2024-08-01   -0.228536
2024-08-02   -2.077157
2024-08-05   -1.458501
2024-08-06   -0.305536
2024-08-07    1.384723
2024-08-08    0.082775
2024-08-09    1.174535
2024-08-12    0.125334
2024-08-13    0.364723
2024-08-14   -0.353447
2024-08-15   -0.024652
2024-08-16    1.876304
2024-08-19    0.799821
2024-08-20   -0.332906
2024-08-21   -0.685682
2024-08-22    1.437468
2024-08-23   -0.163825
2024-08-26    1.059674
2024-08-27    0.426657
2024-08-28   -1.019435
2024-08-29    0.530572
2024-08-30    1.139921
2024-09-02   -1.651556
2024-09-03   -0.228807
2024-09-04   -1.099909
2024-09-05   -0.074691
2024-09-09   -1.417883
2024-09-10    0.215904
2024-09-11   -0.727505
2024-09-12    0.769665
2024-09-13    0.746498
2024-09-16    0.305308
2024-09-17    1.365508
2024-09-19    1.999662
2024-09-20    1.362394
2024-09-23   -0.062770
2024-09-24    4.129154
2024-09-25    0.676501
2024-09-26    4.158484
2024-09-27    3.551998
Name: Close, dtype: float64

In [54]:
(S_daily_return.loc["2024-08-01":]>1).sum()

12

In [57]:
(S_daily_return>1).loc["2024-08-01":].sum()

12

## Filtering on pandas dataframe

In [20]:
df

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-01-02,28249.369141,28543.519531,28245.970703,28543.519531,28543.519531,1262732800
2020-01-03,28828.359375,28883.300781,28428.169922,28451.500000,28451.500000,1797904800
2020-01-06,28326.500000,28367.869141,28054.289062,28226.189453,28226.189453,1793426600
2020-01-07,28352.679688,28473.080078,28264.070312,28322.060547,28322.060547,1302687200
2020-01-08,27999.580078,28198.609375,27857.730469,28087.919922,28087.919922,1709241600
...,...,...,...,...,...,...
2024-12-18,19884.539062,19953.529297,19802.220703,19864.550781,19864.550781,2288100000
2024-12-19,19610.099609,19849.029297,19591.490234,19752.509766,19752.509766,2385000000
2024-12-20,19697.060547,19875.900391,19692.679688,19720.699219,19720.699219,3501200000
2024-12-23,19843.650391,19937.390625,19746.460938,19883.130859,19883.130859,3403600000
2024-12-24,19911.500000,20165.460938,19908.570312,20098.289062,20098.289062,2206500000

In [59]:
df["Daily_return"]=100*(df["Close"]-df["Close"].shift())/df["Close"].shift()

In [60]:
df.tail()

,Open,High,Low,Close,Adj Close,Volume,Daily_return
Date,,,,,,,
2024-09-23,18237.410156,18426.919922,18212.580078,18247.109375,18247.109375,2724524400,-0.062770
2024-09-24,18573.919922,19002.050781,18532.279297,19000.560547,19000.560547,6008421400,4.129154
2024-09-25,19592.429688,19592.429688,19072.720703,19129.099609,19129.099609,6507488700,0.676501
2024-09-26,19302.570312,19954.060547,19176.580078,19924.580078,19924.580078,7428256300,4.158484
2024-09-27,20446.740234,20743.199219,20268.630859,20632.300781,20632.300781,9656093400,3.551998

In [61]:
df["Daily_return"]>1

Date
2020-01-02    False
2020-01-03    False
2020-01-06    False
2020-01-07    False
2020-01-08    False
              ...
2024-09-23    False
2024-09-24     True
2024-09-25    False
2024-09-26     True
2024-09-27     True
Name: Daily_return, Length: 1167, dtype: bool

In [62]:
df[df["Daily_return"]>1]

,Open,High,Low,Close,Adj Close,Volume,Daily_return
Date,,,,,,,
2020-01-09,28367.650391,28561.000000,28325.859375,28561.000000,28561.000000,1692786200,1.684283
2020-01-13,28772.369141,28971.400391,28671.839844,28954.939453,28954.939453,1765055700,1.106006
2020-01-22,28116.500000,28393.929688,27937.679688,28341.039062,28341.039062,1343288100,1.271055
2020-02-04,26491.660156,26730.259766,26491.660156,26675.980469,26675.980469,2500238100,1.210306
2020-02-06,27174.529297,27608.220703,27029.490234,27493.699219,27493.699219,2249533900,2.639212
...,...,...,...,...,...,...,...
2024-09-19,17633.929688,18071.099609,17602.449219,18013.160156,18013.160156,3436673300,1.999662
2024-09-20,18069.330078,18355.150391,18047.130859,18258.570312,18258.570312,4005306800,1.362394
2024-09-24,18573.919922,19002.050781,18532.279297,19000.560547,19000.560547,6008421400,4.129154
2024-09-26,19302.570312,19954.060547,19176.580078,19924.580078,19924.580078,7428256300,4.158484
2024-09-27,20446.740234,20743.199219,20268.630859,20632.300781,20632.300781,9656093400,3.551998

In [65]:
df[(df["Close"]>=20000) & (df["Daily_return"]>1)]

,Open,High,Low,Close,Adj Close,Volume,Daily_return
Date,,,,,,,
2020-01-09,28367.650391,28561.000000,28325.859375,28561.000000,28561.000000,1692786200,1.684283
2020-01-13,28772.369141,28971.400391,28671.839844,28954.939453,28954.939453,1765055700,1.106006
2020-01-22,28116.500000,28393.929688,27937.679688,28341.039062,28341.039062,1343288100,1.271055
2020-02-04,26491.660156,26730.259766,26491.660156,26675.980469,26675.980469,2500238100,1.210306
2020-02-06,27174.529297,27608.220703,27029.490234,27493.699219,27493.699219,2249533900,2.639212
...,...,...,...,...,...,...,...
2023-03-29,20348.640625,20437.689453,20107.730469,20192.400391,20192.400391,2597427400,2.060941
2023-04-17,20374.509766,20864.740234,20299.150391,20782.449219,20782.449219,3411232600,1.681305
2023-05-08,20128.179688,20321.740234,20081.699219,20297.029297,20297.029297,4288098900,1.235547
2023-06-16,19915.439453,20155.919922,19876.419922,20040.369141,20040.369141,3582368700,1.066368
2024-09-27,20446.740234,20743.199219,20268.630859,20632.300781,20632.300781,9656093400,3.551998

In [66]:
df[(df["Close"]>=20000) & (df["Daily_return"]>1)].loc["2023-01-01":]

,Open,High,Low,Close,Adj Close,Volume,Daily_return
Date,,,,,,,
2023-01-03,19570.429688,20212.550781,19303.730469,20145.289062,20145.289062,2286651100,1.839499
2023-01-04,20319.980469,20793.109375,20233.390625,20793.109375,20793.109375,3015986300,3.215741
2023-01-05,21295.869141,21396.089844,20962.400391,21052.169922,21052.169922,2875372400,1.245896
2023-01-09,21295.939453,21470.689453,21216.919922,21388.339844,21388.339844,2697924400,1.889796
2023-01-13,21605.070312,21770.080078,21474.980469,21738.660156,21738.660156,2463604200,1.043783
2023-01-20,21812.460938,22051.769531,21754.349609,22044.650391,22044.650391,1956241900,1.818254
2023-01-26,22386.369141,22566.779297,22329.070312,22566.779297,22566.779297,2455079700,2.368506
2023-02-01,21920.800781,22072.179688,21703.599609,22072.179688,22072.179688,2548571000,1.052313
2023-02-09,21154.250000,21637.550781,21151.269531,21624.359375,21624.359375,1933829700,1.601426
2023-03-01,19849.970703,20674.070312,19849.970703,20619.710938,20619.710938,2889639700,4.213960
2023-03-23,19619.740234,20051.259766,19523.500000,20049.640625,20049.640625,2531213200,2.338834
2023-03-29,20348.640625,20437.689453,20107.730469,20192.400391,20192.400391,2597427400,2.060941
2023-04-17,20374.509766,20864.740234,20299.150391,20782.449219,20782.449219,3411232600,1.681305
2023-05-08,20128.179688,20321.740234,20081.699219,20297.029297,20297.029297,4288098900,1.235547
2023-06-16,19915.439453,20155.919922,19876.419922,20040.369141,20040.369141,3582368700,1.066368
2024-09-27,20446.740234,20743.199219,20268.630859,20632.300781,20632.300781,9656093400,3.551998

## Data Aggregation

In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
'data': range(6)}, columns=['key', 'data'])
print(df)

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [2]:
df.groupby("key").sum()

     data
key
A       3
B       5
C       7

In [3]:
df1 = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
'data': range(6),"data1":[10,20,40,50,70,100]})

In [4]:
df1

  key  data  data1
0   A     0     10
1   B     1     20
2   C     2     40
3   A     3     50
4   B     4     70
5   C     5    100

In [6]:
df1.groupby("key").sum()

     data  data1
key
A       3     60
B       5     90
C       7    140

In [7]:
df_sum=df1.groupby("key").aggregate({"data":"sum","data1":"max"})

In [8]:
df_sum

     data  data1
key
A       3     50
B       5     70
C       7    100

## Example

In [52]:
df=yf.download("^HSI","2020-01-01")

[*********************100%***********************]  1 of 1 completed

In [53]:
df.tail()

Price              Close          High           Low          Open      Volume
Ticker              ^HSI          ^HSI          ^HSI          ^HSI        ^HSI
Date
2025-03-03  23006.269531  23405.980469  22861.750000  23135.119141  4338200000
2025-03-04  22941.769531  23051.009766  22547.529297  22678.250000  3994800000
2025-03-05  23594.210938  23636.650391  23090.630859  23200.419922  4077700000
2025-03-06  24369.710938  24410.929688  23987.089844  23987.089844  4886300000
2025-03-07  24231.300781  24669.619141  24065.009766  24182.019531  4830800000

In [54]:
df1=pd.DataFrame({"High":df["High"]["^HSI"],"Low":df["Low"]["^HSI"]})

In [55]:
df1

                    High           Low
Date
2020-01-02  28543.519531  28245.970703
2020-01-03  28883.300781  28428.169922
2020-01-06  28367.869141  28054.289062
2020-01-07  28473.080078  28264.070312
2020-01-08  28198.609375  27857.730469
...                  ...           ...
2025-03-03  23405.980469  22861.750000
2025-03-04  23051.009766  22547.529297
2025-03-05  23636.650391  23090.630859
2025-03-06  24410.929688  23987.089844
2025-03-07  24669.619141  24065.009766

[1274 rows x 2 columns]

In [56]:
df1["Date1"]=df1.index

In [57]:
df1["Year"]=df1["Date1"].dt.year
df1["Month"]=df1["Date1"].dt.month

In [58]:
df1

                    High           Low      Date1  Year  Month
Date
2020-01-02  28543.519531  28245.970703 2020-01-02  2020      1
2020-01-03  28883.300781  28428.169922 2020-01-03  2020      1
2020-01-06  28367.869141  28054.289062 2020-01-06  2020      1
2020-01-07  28473.080078  28264.070312 2020-01-07  2020      1
2020-01-08  28198.609375  27857.730469 2020-01-08  2020      1
...                  ...           ...        ...   ...    ...
2025-03-03  23405.980469  22861.750000 2025-03-03  2025      3
2025-03-04  23051.009766  22547.529297 2025-03-04  2025      3
2025-03-05  23636.650391  23090.630859 2025-03-05  2025      3
2025-03-06  24410.929688  23987.089844 2025-03-06  2025      3
2025-03-07  24669.619141  24065.009766 2025-03-07  2025      3

[1274 rows x 5 columns]

In [59]:
dfM=df1.groupby(["Year","Month"]).aggregate({"High":"max","Low":"min"})

In [61]:
dfM

                    High           Low
Year Month
2020 1      29174.919922  26295.490234
     2      28055.580078  25989.410156
     3      26805.580078  21139.259766
     4      24855.470703  22756.130859
     5      24766.830078  22519.730469
...                  ...           ...
2024 11     21355.439453  19054.400391
     12     21070.050781  19386.820312
2025 1      20337.460938  18671.490234
     2      24076.529297  19764.669922
     3      24669.619141  22547.529297

[63 rows x 2 columns]

In [62]:
dfM.reset_index(inplace=True)

In [63]:
dfM.head()

   Year  Month          High           Low
0  2020      1  29174.919922  26295.490234
1  2020      2  28055.580078  25989.410156
2  2020      3  26805.580078  21139.259766
3  2020      4  24855.470703  22756.130859
4  2020      5  24766.830078  22519.730469

In [65]:
dfM["Range"]=dfM["High"]-dfM["Low"]

In [66]:
dfM

    Year  Month          High           Low        Range
0   2020      1  29174.919922  26295.490234  2879.429688
1   2020      2  28055.580078  25989.410156  2066.169922
2   2020      3  26805.580078  21139.259766  5666.320312
3   2020      4  24855.470703  22756.130859  2099.339844
4   2020      5  24766.830078  22519.730469  2247.099609
..   ...    ...           ...           ...          ...
58  2024     11  21355.439453  19054.400391  2301.039062
59  2024     12  21070.050781  19386.820312  1683.230469
60  2025      1  20337.460938  18671.490234  1665.970703
61  2025      2  24076.529297  19764.669922  4311.859375
62  2025      3  24669.619141  22547.529297  2122.089844

[63 rows x 5 columns]

In [67]:
dfM.groupby("Month").aggregate({"Range":"mean"})

             Range
Month
1      2611.304688
2      2651.908366
3      3032.158529
4      1883.763867
5      2069.207812
6      1579.521875
7      2397.675391
8      1906.596484
9      2762.566016
10     2418.420117
11     2555.439844
12     1487.459961

In [68]:
dfM.groupby("Month").aggregate({"Range":["mean","max","min","std"]})

             Range
              mean          max          min          std
Month
1      2611.304688  3397.119141  1665.970703   635.860109
2      2651.908366  4311.859375  1558.959961   930.645991
3      3032.158529  5666.320312  1118.990234  1751.506332
4      1883.763867  2858.150391  1130.849609   682.820210
5      2069.207812  2276.880859  1620.250000   280.630845
6      1579.521875  1965.650391  1141.429688   352.784485
7      2397.675391  4110.179688  1392.730469  1015.497744
8      1906.596484  2757.580078  1094.050781   626.288531
9      2762.566016  4524.470703  1546.660156  1116.621035
10     2418.420117  3566.889648  1296.070312  1040.066785
11     2555.439844  3785.429688  1311.638672   892.825489
12     1487.459961  1720.189453  1122.809570   251.606290